export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const CABINET_ROUTE = '/cabinet'
export const PORTFOLIO_ROUTE = '/portfolio'
export const PAYMENT_STATUS_ROUTE = '/payment-status'
